2019-11-28 12:21:27,756 ERROR: Exception on /index [GET] [in /home/zordo/micro_blog/venv_f/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/zordo/micro_blog/venv_f/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/zordo/micro_blog/venv_f/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/zordo/micro_blog/venv_f/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/zordo/micro_blog/venv_f/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/zordo/micro_blog/venv_f/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/zordo/micro_blog/venv_f/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/zordo/micro_blog/venv_f/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/zordo/micro_blog/app/routes.py", line 32, in index
    return render_template('index.html',title ='Home Page', posts= posts )
  File "/home/zordo/micro_blog/venv_f/lib/python3.6/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/home/zordo/micro_blog/venv_f/lib/python3.6/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/zordo/micro_blog/venv_f/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/zordo/micro_blog/venv_f/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/zordo/micro_blog/venv_f/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/zordo/micro_blog/venv_f/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/zordo/micro_blog/app/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/zordo/micro_blog/app/templates/base.html", line 30, in top-level template code
    {% block content %}{% endblock %}
  File "/home/zordo/micro_blog/app/templates/index.html", line 6, in block "content"
    {{ form.hidden_tag() }}
  File "/home/zordo/micro_blog/venv_f/lib/python3.6/site-packages/jinja2/environment.py", line 430, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
2019-11-28 12:21:37,074 ERROR: Exception on /index [GET] [in /home/zordo/micro_blog/venv_f/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/zordo/micro_blog/venv_f/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/zordo/micro_blog/venv_f/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/zordo/micro_blog/venv_f/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/zordo/micro_blog/venv_f/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/zordo/micro_blog/venv_f/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/zordo/micro_blog/venv_f/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/zordo/micro_blog/venv_f/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/zordo/micro_blog/app/routes.py", line 32, in index
    return render_template('index.html',title ='Home Page', posts= posts )
  File "/home/zordo/micro_blog/venv_f/lib/python3.6/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/home/zordo/micro_blog/venv_f/lib/python3.6/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/zordo/micro_blog/venv_f/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/zordo/micro_blog/venv_f/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/zordo/micro_blog/venv_f/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/zordo/micro_blog/venv_f/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/zordo/micro_blog/app/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/zordo/micro_blog/app/templates/base.html", line 30, in top-level template code
    {% block content %}{% endblock %}
  File "/home/zordo/micro_blog/app/templates/index.html", line 6, in block "content"
    {{ form.hidden_tag() }}
  File "/home/zordo/micro_blog/venv_f/lib/python3.6/site-packages/jinja2/environment.py", line 430, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
2019-11-28 12:22:11,695 INFO: Microblog startup [in /home/zordo/micro_blog/app/__init__.py:47]
2019-11-28 12:22:15,939 INFO: Microblog startup [in /home/zordo/micro_blog/app/__init__.py:47]
2019-11-28 12:22:41,563 INFO: Microblog startup [in /home/zordo/micro_blog/app/__init__.py:47]
2019-11-28 12:22:44,116 ERROR: Exception on / [GET] [in /home/zordo/micro_blog/venv_f/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/zordo/micro_blog/venv_f/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/zordo/micro_blog/venv_f/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/zordo/micro_blog/venv_f/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/zordo/micro_blog/venv_f/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/zordo/micro_blog/venv_f/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/zordo/micro_blog/venv_f/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/zordo/micro_blog/venv_f/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/zordo/micro_blog/app/routes.py", line 32, in index
    return render_template('index.html',title ='Home Page', posts= posts )
  File "/home/zordo/micro_blog/venv_f/lib/python3.6/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/home/zordo/micro_blog/venv_f/lib/python3.6/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/zordo/micro_blog/venv_f/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/zordo/micro_blog/venv_f/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/zordo/micro_blog/venv_f/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/zordo/micro_blog/venv_f/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/zordo/micro_blog/app/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/zordo/micro_blog/app/templates/base.html", line 30, in top-level template code
    {% block content %}{% endblock %}
  File "/home/zordo/micro_blog/app/templates/index.html", line 6, in block "content"
    {{ form.hidden_tag() }}
  File "/home/zordo/micro_blog/venv_f/lib/python3.6/site-packages/jinja2/environment.py", line 430, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
2019-11-28 12:24:11,500 INFO: Microblog startup [in /home/zordo/micro_blog/app/__init__.py:47]
2019-11-28 12:24:28,689 INFO: Microblog startup [in /home/zordo/micro_blog/app/__init__.py:47]
